artifacts:
    ARTIFACTS_DIR : artifacts
    TRAINED_MODEL_DIR : model
    BASE_MODEL_DIR : base_model
    BASE_MODEL_NAME : VGG16_base_model.h5
    UPDATED_WEIGHTS_MODEL : updated_VGG16_model.h5
    CHECKPOINTS_DIR : checkpoints
    BASE_LOG_DIR : base_log
    TENSORBOARD_ROOT_LOG_DIR : tensorboard_log_dir
    CALLBACKS_DIR : callbacks
  
source_download_dir:
      - ../outside_data/dog
      - ../outside_data/cat

local_data_dirs:
  - data/dog
  - data/cat